controllerModule.controller('tasksGroupController',
function($scope,tasksGroupService,$uibModalInstance){
  $scope.createTasksGroup=function(){
    if($scope.tasksGroupForm.$valid){
      tasksGroupService.createTasksGroup($scope.tasksGroup).then(function(response){
        $uibModalInstance.close();
      });
    }
  };
});